### ISSUE TITLE
folders without trailing slash hang fastify

### ISSUE THREAD

**Issue by YnotnaUK** [fastify/fastify-static#105]
i'm using the below to select the public directory

```
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'public')
});
```

inside public is index.html & 3 folders js, css & img as expected

if i browse to:
/css/stylesheet.css --> I get the correct sheet and it works OK
/css/ --> returns 404 which is expected
/css --> fastify hangs and does not return a response and the browser sits waiting for a response

Testing with Google Chrome & Microsoft Edge and both have the same issue

**Comment by Eomm** [comment]
I think there is some bug somewhere, the 404 handler is never reached for the `/css` as you notice.

Tried also `ignoreTrailingSlash` config

```
'use strict'

const Fastify = require('fastify')
const path = require('path')

const app = Fastify({ logger: true, ignoreTrailingSlash: true })

app.register(require('fastify-static'), {
  root: path.join(__dirname, 'public')
});

app.setNotFoundHandler((request, reply) => {
  app.log.warn('404')
  reply.send('404')
})

app.listen(3000)
```

**Comment by humphd** [comment]
I can reproduce this on older commits (e.g., 43706ca01aec4c223c6141aaa3d496a1b9a54b1f) , but not on latest master.  I think this is fixed.

**Comment by ACenterA** [comment]
@mcollina  The bug still exists

I was able to reproduce when using an array for the `root` ie:

```

const app = Fastify({ logger: true, ignoreTrailingSlash: true })

app.register(require('fastify-static'), {
  root: [path.join(__dirname, 'public'), path.join(__dirname, 'test')]
});

```

In my case using an array caused issue, when i used

```
root: arrayOfFolders[0],
```
It didnt hang.

I'm using gz compression and othering

**Comment by mcollina** [comment]
Please open a fresh issue with a example to reproduce, a github repo is ok.

**Comment by mcollina** [comment]
A PR to fix would also be nice.
